In [1]:
import numpy as np
import tifffile as tiff
import matplotlib.pyplot as plt
from importlib import reload
import trackpy as tp

from analysis_pipelines.peak_detection_stationary import peak_detection_stationary
from analysis_pipelines.peak_detection_stationary_dualcolor import peak_detection_stationary_dualcolor

In [2]:
filepath = 'C:\\Users\\alvelidjonatan\\Documents\\Data\\etMINFLUX-lab\\data-pex\\analysis_testing\\teststack-dt25s.tif'
filepath_ch2 = 'C:\\Users\\alvelidjonatan\\Documents\\Data\\etMINFLUX-lab\\data-pex\\analysis_testing\\ch2test.tif'
imstack = tiff.imread(filepath)
imch2 = tiff.imread(filepath_ch2)

In [42]:
import analysis_pipelines.peak_detection_stationary
reload(analysis_pipelines.peak_detection_stationary)
from analysis_pipelines.peak_detection_stationary import peak_detection_stationary

import analysis_pipelines.peak_detection_stationary_dualcolor
reload(analysis_pipelines.peak_detection_stationary_dualcolor)
from analysis_pipelines.peak_detection_stationary_dualcolor import peak_detection_stationary_dualcolor

In [37]:
tracks = None
prev_events = None
for idx, frame in enumerate(imstack):
    coordinates, roi_sizes, img_ana, tracks = peak_detection_stationary(frame, None, None, tracks, None)

EVENT, frame 4
EVENT, frame 4
[[ 69 128]]

EVENT, frame 5
EVENT, frame 5
EVENT, frame 5
[[121 188]]

EVENT, frame 6
[[120 188]]

EVENT, frame 7
EVENT, frame 7
[[152 190]]

EVENT, frame 8
[[203 159]]

EVENT, frame 9
EVENT, frame 9
[[203 160]]

EVENT, frame 10
EVENT, frame 10
EVENT, frame 10
[[155 159]]



In [ ]:
tracks = None
prev_events = None
for idx, frame in enumerate(imstack):
    coordinates, roi_sizes, tracks, img_ch2 = peak_detection_stationary_dualcolor(frame, imch2, None, None, tracks, None)

EVENT, frame 4
[[ 69 128]]

EVENT, frame 5
[[ 69 129]]

EVENT, frame 7
[[152 190]]



In [46]:
tracks

particle  frame      x      y  intensity  intensitych2
0           0      0   20.0  183.0   5.164844      0.125079
93          1      0  200.0  131.0   6.000244      0.024962
94          2      0  200.0  104.0  29.173609      0.153482
86          3      0  186.0  146.0  11.731844      0.083954
82          4      0  173.0   51.0   7.702728      1.283142
..        ...    ...    ...    ...        ...           ...
34         59     10   71.0  121.0  26.883679      0.045653
33        362     10   70.0  161.0   8.328053      0.085902
31        396     10   68.0  182.0  20.543428      0.443306
62        398     10  114.0   82.0  59.687919      0.294484
126       348     10  235.0  126.0   6.794280      0.152081

[1366 rows x 6 columns]